name: Test Build and Run SmallCityMastodonBot

on:
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore SmallCityMastodonBot.csproj

      - name: Build project
        run: dotnet build SmallCityMastodonBot.csproj --configuration Release

      - name: Run project with dummy api key so it doesn't post
        env:
          OVERPASS_PRIMARY_URL: ${{ secrets.OVERPASS_PRIMARY_URL }}
        run: dotnet run --project SmallCityMastodonBot.csproj -- "12345" "UnmappedSmallTownCanada" "/posttown"